#!/bin/bash
# Definir variables para colores de texto
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
GRAY='\033[1;37m'
WHITE='\033[1;37m'
# Definir variables para colores de fondo
BG_RED='\033[0;41m'
BG_GREEN='\033[0;42m'
BG_YELLOW='\033[0;43m'
BG_BLUE='\033[0;44m'
BG_PURPLE='\033[0;45m'
BG_CYAN='\033[0;46m'
BG_GRAY='\033[0;47m'
# Resetear colores
RESET='\033[0m'
clear
slowdns () {
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
figlet -p -f slant SlowDNS
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ────────── Mod SlowDNS VpsPack ───────── ${YELLOW}"
    archivo="/root/server.pub"
    if [ -e "$archivo" ]; then
        echo -ne "${YELLOW}YOUR NS: ${WHITE} " && cat /etc/slowdns/infons
        echo -ne "${YELLOW}YOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
    else
        echo "Not Installed"
    fi
echo -e "${GRAY}[${RED}-${GRAY}]${RED} ───────────────── /// ────────────────── ${YELLOW}"
    echo -e "${YELLOW}[${GREEN}01${YELLOW}]${WHITE} | Install SlowDNS"
    echo -e "${YELLOW}[${GREEN}02${YELLOW}]${WHITE} | See information"
    echo -e "${YELLOW}[${GREEN}03${YELLOW}]${WHITE} | Start SlowDNS"
    echo -e "${YELLOW}[${GREEN}04${YELLOW}]${WHITE} | RESTART SlowDNS"
    echo -e "${YELLOW}[${GREEN}05${YELLOW}]${WHITE} | STOP SlowDNS"
    echo -e "${YELLOW}[${GREEN}06${YELLOW}]${WHITE} | Remove SlowDNS"
    echo -e "${YELLOW}[${GREEN}07${YELLOW}]${WHITE} | Update/Reinstall"
    echo -e "${YELLOW}[${GREEN}08${YELLOW}]${WHITE} | Remove Script"
    echo -e "${YELLOW}[${GREEN}00${YELLOW}]${WHITE} | EXIT"
    echo ""
    echo -ne "${YELLOW}What do you want to do?:\0033[m " && read option
    case $option in
    1|01) Option1 ;;
    2|02) Option2 ;;
    3|03) Option3 ;;
    4|04) Option4 ;;
    5|05) Option5 ;;
    6|06) Option6 ;;
    7|07) Option7 ;;
    8|08) Option8 ;;
    0|00) Sair ;;
    *) "Invalid option" ; echo ; slowdns ;;
    esac
    }

Option1 () {
    clear
    bash /etc/slowdns/slowdns-install
}

Option2 () {
    clear
    bash /etc/slowdns/slowdns-info
}

Option3 () {
    clear
    bash /etc/slowdns/startdns
}

Option4 () {
    clear
    bash /etc/slowdns/restartdns
}

Option5 () {
    clear
    bash /etc/slowdns/stopdns
}

Option6 () {
     clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
}

Option7 () {
    clear
    wget https://raw.githubusercontent.com/powermx/dnstt/main/update
    chmod +x update
    bash update
}

Option8 () {
     clear
    bash /etc/slowdns/remove-slow
    echo -e "\033[0;31mSlowDNS Manager Uninstalled!\033[0m"
    sleep 2
    rm /bin/slowdns
}

Sair() {
    clear
    cd
}
clear
slowdns
